### ISSUE TITLE
[Implement] Basic CRUD Functions + Models

### ISSUE THREAD

**Issue by ihcgamertube** [ihcgamertube/CodeName_WordsDatabaseAPI#1]
- Communicate with MongoDb Local Database

**Comment by nadavni12** [comment]
In lines 13-16, you have used lowercase instead of uppercase for const strings

**Comment by nadavni12** [comment]
Also Note: you should not use a singleton here. This will not scale up greatly. This code can only handle one DB for the whole game project.
